name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: run npm common tasks
        uses: ./.github/actions
        with:
          node-version: "16.15.0"
      - name: deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain greedy-boat.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
