name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set node version
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: install dependencies
        run: npm ci
      - name: run linter
        run: npm run format:check
      - name: run tests
        run: npm run test -- --coverage
        env:
          CI: true
      - name: build project
        if: github.event_name == "push"
        run: npm run build
      - name: deploy to staging
        if: github.event_name == "push"
        run: npx surge --project ./build --domain greedy-boat.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
