name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set node version
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: install dependencies
        run: npm ci
      - name: run linter
        run: npm run format:check
      - name: run tests
        run: npm run test -- --coverage
        env:
          CI: true
